'use strict';

exports.BattleLearnsets = {
    tropius: {learnset: { //NOT DONE
        aerialace: ["6M", "5M", "4M", "3M"],
        aircutter: ["4T"],
        airslash: ["6L36", "5L51", "4L47", "4S0"],
        attract: ["6M", "5M", "4M", "3M"],
        bestow: ["6L1", "5L57"],
        bodyslam: ["6L37", "5L37", "4L37", "3T", "3L37"],
        bulldoze: ["6M", "5M"],
        bulletseed: ["6E", "5E", "4M", "3M"],
        captivate: ["4M"],
        confide: ["6M"],
        curse: ["6E", "5E", "4E"],
        cut: ["6M", "5M", "4M", "3M"],
        defog: ["4M"],
        doubleedge: ["3T"],
        doubleteam: ["6M", "5M", "4M", "3M"],
        dragondance: ["6E", "5E", "4E"],
        dragonpulse: ["6T", "5T"],
        earthquake: ["6M", "5M", "4M", "3M"],
        endure: ["4M", "3T"],
        energyball: ["6M", "5M", "4M"],
        facade: ["6M", "5M", "4M", "3M"],
        flash: ["6M", "5M", "4M", "3M"],
        fly: ["6M", "5M", "4M", "3M"],
        frustration: ["6M", "5M", "4M", "3M"],
        furycutter: ["4T", "3T"],
        gigadrain: ["6T", "5T", "4M", "3M"],
        gigaimpact: ["6M", "5M", "4M"],
        grassknot: ["6M", "5M", "4M"],
        growth: ["6L1", "5L7", "4L7", "3L7"],
        gust: ["6L1", "5L1", "5D", "4L1", "3L1"],
        headbutt: ["6E", "5E", "4T", "4E", "3E"],
        hiddenpower: ["6M", "5M", "4M", "3M"],
        hyperbeam: ["6M", "5M", "4M", "3M"],
        leafblade: ["6E", "5E", "4E"],
        leafstorm: ["6L1", "6E", "5L71", "5E", "4L61", "4E"],
        leaftornado: ["6L26", "5L47"],
        leechseed: ["6E", "5E", "5D", "4E", "3E"],
        leer: ["6L1", "5L1", "4L1", "3L1"],
        magicalleaf: ["6L16", "5L31", "4L31", "3L31"],
        mimic: ["3T"],
        mudslap: ["4T", "3T"],
        naturalgift: ["6L1", "6E", "5L67", "5E", "4M", "4L57"],
        naturepower: ["6M", "6E", "5E", "4E", "3E"],
        ominouswind: ["4T"],
        outrage: ["6T", "5T", "4T"],
        protect: ["6M", "5M", "4M", "3M"],
        razorleaf: ["6L1", "5L11", "4L11", "3L11"],
        razorwind: ["6E", "5E", "4E", "3E"],
        rest: ["6M", "5M", "4M", "3M"],
        return: ["6M", "5M", "4M", "3M"],
        roar: ["6M", "5M", "4M", "3M"],
        rocksmash: ["6M", "5M", "4M", "3M"],
        roost: ["6M", "5T", "4M"],
        round: ["6M", "5M"],
        safeguard: ["6M", "5M", "4M", "3M"],
        secretpower: ["6M", "4M", "3M"],
        seedbomb: ["6T", "5T"],
        silverwind: ["5D", "4M"],
        slam: ["6E", "5E", "4E", "3E"],
        sleeptalk: ["6M", "5T", "4M", "3T"],
        snore: ["6T", "5T", "4T", "3T"],
        solarbeam: ["6M", "6L56", "5M", "5L61", "4M", "4L51", "4S0", "3M", "3L41"],
        steelwing: ["6M", "4M", "3M"],
        stomp: ["6L10", "5L17", "4L17", "3L17"],
        strength: ["6M", "5M", "4M", "3M"],
        substitute: ["6M", "5M", "4M", "3T"],
        sunnyday: ["6M", "5M", "4M", "4S0", "3M"],
        swagger: ["6M", "5M", "4M", "3T"],
        sweetscent: ["6L6", "5L21", "4L21", "3L21"],
        swordsdance: ["6M", "5M", "4M", "3T"],
        synthesis: ["6T", "6L41", "6E", "5T", "5L41", "5E", "4T", "4L41", "4E", "4S0", "3L47"],
        tailwind: ["6T", "5T", "4T"],
        toxic: ["6M", "5M", "4M", "3M"],
        twister: ["4T"],
        whirlwind: ["6L21", "5L27", "4L27", "3L27"],
        worryseed: ["6T", "5T", "4T"],
        //custom
        morningsun: ["6M"],
        seedflare: ["6M"],
        fierydance: ["6M"]

    }},
    avalugg: {learnset: {
        afteryou: ["6T"],
        attract: ["6M"],
        avalanche: ["6L42"],
        bite: ["6L1"],
        blizzard: ["6M", "6L46"],
        block: ["6T"],
        bulldoze: ["6M"],
        confide: ["6M"],
        crunch: ["6L1"],
        curse: ["6L22"],
        doubleedge: ["6L56"],
        doubleteam: ["6M"],
        earthquake: ["6M"],
        facade: ["6M"],
        flash: ["6M"],
        flashcannon: ["6M"],
        frostbreath: ["6M"],
        frustration: ["6M"],
        gigaimpact: ["6M"],
        gyroball: ["6M"],
        hail: ["6M"],
        harden: ["6L1"],
        hiddenpower: ["6M"],
        hyperbeam: ["6M"],
        iceball: ["6L30"],
        icebeam: ["6M"],
        icefang: ["6L26"],
        icywind: ["6T", "6L10"],
        irondefense: ["6T", "6L1"],
        ironhead: ["6T"],
        powdersnow: ["6L5"],
        protect: ["6M"],
        raindance: ["6M"],
        rapidspin: ["6L35"],
        recover: ["6L51"],
        rest: ["6M"],
        return: ["6M"],
        roar: ["6M"],
        rockpolish: ["6M"],
        rockslide: ["6M"],
        rocksmash: ["6M"],
        rocktomb: ["6M"],
        round: ["6M"],
        safeguard: ["6M"],
        secretpower: ["6M"],
        sharpen: ["6L20"],
        skullbash: ["6L1"],
        sleeptalk: ["6M"],
        snore: ["6T"],
        stoneedge: ["6M"],
        strength: ["6M"],
        substitute: ["6M"],
        superpower: ["6T"],
        surf: ["6M"],
        swagger: ["6M"],
        tackle: ["6L1"],
        takedown: ["6L15"],
        toxic: ["6M"],
        waterpulse: ["6T"],
        //custom
        iciclecrash: ["6M"]


    }},
    delibird: {learnset: {
        aerialace: ["6M", "5M", "4M", "3M"],
        attract: ["6M", "5M", "4M", "3M"],
        aurorabeam: ["6E", "5E", "4E", "3E"],
        avalanche: ["4M"],
        bestow: ["6E", "5E"],
        blizzard: ["6M", "5M", "4M", "3M"],
        bodyslam: ["3T"],
        bounce: ["6T", "5T", "4T"],
        brickbreak: ["6M", "5M", "4M"],
        captivate: ["4M"],
        confide: ["6M"],
        counter: ["3T"],
        defog: ["4M"],
        destinybond: ["6E"],
        doubleedge: ["3T"],
        doubleteam: ["6M", "5M", "4M", "3M"],
        endure: ["4M", "3T"],
        facade: ["6M", "5M", "4M", "3M"],
        fakeout: ["6E", "5E", "4E"],
        fling: ["6M", "5M", "4M"],
        fly: ["6M", "5M", "4M", "3M"],
        focuspunch: ["6T", "5D", "4M", "3M"],
        freezedry: ["6E"],
        frostbreath: ["6M", "5M"],
        frustration: ["6M", "5M", "4M", "3M"],
        futuresight: ["6E", "5E", "4E", "3E"],
        gunkshot: ["6T", "5T", "4T"],
        hail: ["6M", "5M", "4M", "3M"],
        happyhour: ["6S1"],
        headbutt: ["4T"],
        hiddenpower: ["6M", "5M", "4M", "3M"],
        iceball: ["6E", "5E", "4E", "3E"],
        icebeam: ["6M", "5M", "4M", "3M"],
        icepunch: ["6T", "6E", "5T", "5E", "4E"],
        iceshard: ["6E", "5E", "5D", "4E"],
        icywind: ["6T", "6E", "5T", "5E", "4T", "3T"],
        megakick: ["3T"],
        megapunch: ["3T"],
        mimic: ["3T"],
        mudslap: ["4T", "3T"],
        naturalgift: ["4M"],
        pluck: ["5M", "4M"],
        poweruppunch: ["6M"],
        present: ["6L1", "6S1", "5L1", "5D", "4L1", "3L1", "3S0"],
        protect: ["6M", "5M", "4M", "3M"],
        quickattack: ["6E", "5E", "4E", "3E"],
        raindance: ["6M", "5M", "4M", "3M"],
        rapidspin: ["6E", "5E", "4E", "3E"],
        recycle: ["6T", "5T", "4M"],
        rest: ["6M", "5M", "4M", "3M"],
        return: ["6M", "5M", "4M", "3M"],
        rollout: ["4T"],
        round: ["6M", "5M"],
        secretpower: ["6M", "4M", "3M"],
        seedbomb: ["6T", "5T", "4T"],
        seismictoss: ["3T"],
        signalbeam: ["6T", "5T", "4T"],
        skyattack: ["6T", "5T", "4T", "3T"],
        sleeptalk: ["6M", "5T", "4M", "3T"],
        snore: ["6T", "3T"],
        spikes: ["6E"],
        splash: ["6E", "5E", "4E", "3E"],
        substitute: ["6M", "5M", "4M", "3T"],
        swagger: ["6M", "5M", "4M", "3T"],
        swift: ["4T", "3T"],
        thief: ["6M", "5M", "4M", "3M"],
        toxic: ["6M", "5M", "4M", "3M"],
        waterpulse: ["6T", "4M", "3M"],
        //custom
        iciclecrash: ["6M"],
        iciclespear: ["6M"]

    }},
    golduck: {learnset: {
        aerialace: ["6M", "5M", "4M", "3M"],
        amnesia: ["6L49", "5L56", "4L50"],
        aquajet: ["6L1", "5L1", "4L1"],
        aquatail: ["6T", "6L32", "5T", "5L32", "4T"],
        attract: ["6M", "5M", "4M", "3M"],
        blizzard: ["6M", "5M", "4M", "3M"],
        bodyslam: ["3T"],
        brickbreak: ["6M", "5M", "4M", "3M", "3S0"],
        brine: ["4M"],
        calmmind: ["6M", "5M", "4M", "3M"],
        captivate: ["4M"],
        charm: ["3S0"],
        confide: ["6M"],
        confusion: ["6L11", "5L18", "4L18", "3L16"],
        counter: ["3T"],
        dig: ["6M", "5M", "4M", "3M"],
        disable: ["6L11", "5L14", "4L14", "3L1"],
        dive: ["6M", "5M", "4T", "3M"],
        doubleedge: ["3T"],
        doubleteam: ["6M", "5M", "4M", "3M"],
        dynamicpunch: ["3T"],
        endure: ["4M", "3T"],
        facade: ["6M", "5M", "4M", "3M"],
        flash: ["6M", "5M", "4M", "3M"],
        fling: ["6M", "5M", "4M"],
        focusblast: ["6M", "5M", "4M"],
        focuspunch: ["6T", "4M", "3M"],
        frustration: ["6M", "5M", "4M", "3M"],
        furycutter: ["4T", "3T"],
        furyswipes: ["6L15", "5L27", "4L27", "3L44"],
        gigaimpact: ["6M", "5M", "4M"],
        hail: ["6M", "5M", "4M", "3M"],
        headbutt: ["4T"],
        hiddenpower: ["6M", "5M", "4M", "3M"],
        honeclaws: ["6M", "5M"],
        hydropump: ["6L54", "5L63", "4L56", "3L58"],
        hyperbeam: ["6M", "5M", "4M", "3M"],
        icebeam: ["6M", "5M", "4M", "3M"],
        icepunch: ["6T", "5T", "4T", "3T"],
        icywind: ["6T", "5T", "4T", "3T"],
        irontail: ["6T", "5T", "4M", "3M"],
        lightscreen: ["6M", "5M"],
        lowkick: ["6T", "5T", "4T"],
        lowsweep: ["6M", "5M"],
        megakick: ["3T"],
        megapunch: ["3T"],
        mimic: ["3T"],
        mudslap: ["4T", "3T"],
        naturalgift: ["4M"],
        poweruppunch: ["6M"],
        protect: ["6M", "5M", "4M", "3M"],
        psychic: ["6M", "5M", "4M"],
        psychup: ["6M", "6L43", "5M", "5L44", "4M", "4L37", "3T", "3L31", "3S0"],
        psyshock: ["6M", "5M"],
        raindance: ["6M", "5M", "4M", "3M"],
        rest: ["6M", "5M", "4M", "3M"],
        return: ["6M", "5M", "4M", "3M"],
        rockclimb: ["4M"],
        rocksmash: ["6M", "5M", "4M", "3M"],
        roleplay: ["6T", "5T", "4T"],
        round: ["6M", "5M"],
        scald: ["6M", "5M"],
        scratch: ["6L1", "5L1", "4L1", "3L1"],
        screech: ["6L25", "5L31", "4L31", "3L23"],
        secretpower: ["6M", "4M", "3M"],
        seismictoss: ["3T"],
        shadowclaw: ["6M", "5M", "4M"],
        signalbeam: ["6T", "5T", "4T"],
        sleeptalk: ["6M", "5T", "4M", "3T"],
        snore: ["6T", "5T", "4T", "3T"],
        soak: ["6L38", "5L37"],
        strength: ["6M", "5M", "4M", "3M"],
        substitute: ["6M", "5M", "4M", "3T"],
        surf: ["6M", "5M", "4M", "3M"],
        swagger: ["6M", "5M", "4M", "3T"],
        swift: ["4T", "3T"],
        tailwhip: ["6L1", "5L1", "4L1", "3L1"],
        telekinesis: ["5M"],
        toxic: ["6M", "5M", "4M", "3M"],
        waterfall: ["6M", "5M", "4M", "3M", "3S0"],
        watergun: ["6L1", "5L1", "4L1"],
        waterpulse: ["6T", "6L18", "5L22", "4M", "4L22", "3M"],
        watersport: ["6L1", "5L1", "4L1", "3L1"],
        whirlpool: ["4M"],
        wonderroom: ["6T", "6L60", "5T", "5L69"],
        worryseed: ["6T", "5T", "4T"],
        zenheadbutt: ["6T", "6L25", "5T", "5L50", "4T", "4L44"],
        //custom
        aurasphere: ["6M"],
        thunderbolt: ["6M"]

    }},
    flygon: {learnset: {
        aerialace: ["6M", "5M", "4M"],
        aircutter: ["4T"],
        attract: ["6M", "5M", "4M", "3M"],
        bide: ["6L1", "5L17"],
        bite: ["3L1"],
        bodyslam: ["3T"],
        bugbite: ["6T", "5T", "4T"],
        bulldoze: ["6M", "6L8", "5M", "5L21"],
        captivate: ["4M"],
        confide: ["6M"],
        crunch: ["3L33", "3S0"],
        defog: ["4M"],
        dig: ["6M", "5M", "4M", "3M"],
        doubleedge: ["3T"],
        doubleteam: ["6M", "5M", "4M", "3M"],
        dracometeor: ["6T", "5T", "4T", "4S1"],
         dragonbreath: ["6L35", "5L35", "4L35", "3L35", "3S0"],
        dragonclaw: ["6M", "6L45", "5M", "5L45", "4M", "4L45", "4S1", "3M"],
        dragonpulse: ["6T", "5T", "4M"],
        dragonrush: ["6L47"],
        dragontail: ["6M", "6L29", "5M", "5L65"],
        earthpower: ["6T", "6L26", "5T", "5L39", "4T"],
        earthquake: ["6M", "6L33", "5M", "4M", "4S1", "3M"],
        endure: ["4M", "3T"],
        facade: ["6M", "5M", "4M", "3M"],
        feintattack: ["6L1", "5L1", "4L1", "3L1"],
        fireblast: ["6M", "5M", "4M", "3M"],
        firepunch: ["6T", "5T", "4T", "3T"],
        flamethrower: ["6M", "5M", "4M", "3M"],
        fly: ["6M", "5M", "4M", "3M"],
        frustration: ["6M", "5M", "4M", "3M"],
        furycutter: ["4T", "3T"],
        gigadrain: ["6T", "5T", "4M", "3M"],
        gigaimpact: ["6M", "5M", "4M"],
        headbutt: ["4T"],
        heatwave: ["6T", "5T", "4T"],
        hiddenpower: ["6M", "5M", "4M", "3M"],
        honeclaws: ["6M", "5M"],
        hyperbeam: ["6M", "6L43", "5M", "5L57", "4M", "4L57", "3M", "3L65"],
        incinerate: ["6M", "5M"],
        irontail: ["6T", "5T", "4M", "3M"],
        mimic: ["3T"],
        mudslap: ["6L5", "5L13", "4T", "3T"],
        naturalgift: ["4M"],
        ominouswind: ["4T"],
        outrage: ["6T", "5T", "4T"],
        poweruppunch: ["6M"],
        protect: ["6M", "5M", "4M", "3M"],
        rest: ["6M", "5M", "4M", "3M"],
        return: ["6M", "5M", "4M", "3M"],
        rockslide: ["6M", "6L15", "5M", "5L25", "4M", "3T"],
        rocksmash: ["6M", "5M", "4M", "3M"],
        rocktomb: ["6M", "5M", "4M", "3M"],
        roost: ["6M", "5T", "4M"],
        round: ["6M", "5M"],
        sandattack: ["6L1", "5L1", "4L1", "3L1"],
        sandstorm: ["6M", "6L36", "5M", "5L49", "4M", "4L49", "3M", "3L53"],
        sandtomb: ["6L1", "5L1", "4L1", "3L1", "3S0"],
        screech: ["6L22", "5L41", "4L41", "3L41", "3S0"],
        secretpower: ["6M", "4M", "3M"],
        signalbeam: ["6T", "5T"],
        silverwind: ["4M"],
        sleeptalk: ["6M", "5T", "4M", "3T"],
        snore: ["6T", "5T", "4T", "3T"],
        solarbeam: ["6M", "5M", "4M", "3M"],
        sonicboom: ["6L1", "5L1", "4L1"],
        steelwing: ["6M", "4M", "3M"],
        stoneedge: ["6M", "5M", "4M"],
        strength: ["6M", "5M", "4M", "3M"],
        strugglebug: ["6M", "5M"],
        substitute: ["6M", "5M", "4M", "3T"],
        sunnyday: ["6M", "5M", "4M", "3M"],
        superpower: ["6T", "5T"],
        supersonic: ["6L19", "5L33", "4L33"],
        swagger: ["6M", "5M", "4M", "3T"],
        swift: ["4T", "3T"],
        tailwind: ["6T", "5T", "4T"],
        thunderpunch: ["6T", "5T", "4T"],
        toxic: ["6M", "5M", "4M", "3M"],
        twister: ["4T"],
        uproar: ["6T", "6L40"],
        uturn: ["6M", "5M", "4M", "4S1"],
        //custom
        xscissor: ["6M"]

    }},
}
